name: auto-commit
on:
  push:
    branches:
      - main
  schedule:
      - cron: "* * * * *"
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: commit
        run: |
          git config --local user.email "haha@haha.com"
          git config --local user.name "haha"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "auto-commit"
          git push
